### PR TITLE
change project authors

### PR DESCRIPTION
**Pull request by mattip**
@tdimitri @kcpevey does this look right?

### CODE REVIEW

**Review by kcpevey — APPROVED** [review]
LGTM

**Comment by mattip** [comment]
In discussions with @jack-pappas and @tdimitri they would prefer a different name as author. @rpekrul did you catch what it should be?

**Comment by tdimitri** [comment]
instead of https://sig.com please use https://github.com/rtosholdings

**Comment by rpekrul** [comment]
@kcpevey ^^ Please see project author.

**Comment by kcpevey** [comment]
@mattip so sorry, but I managed to mess up the git history on your fork. Since I'm in a time crunch and these changes are minor, I moved the required changes to a new PR https://github.com/Quansight/numpy-threading-extensions/pull/63

**Pull request closed without merging**
