### PR TITLE
Rever

### PR DESCRIPTION
**Pull request by daletovar**
These are the changes made by rever using the following activities:
- 'version_bump'
- 'changelog'
- 'tag'
- 'push_tag'           

when I try to use 'ghrelease' I get an error. I'm working on figuring it out.

### CODE REVIEW

**Comment by daletovar** [comment]
```
(base) dale@dale-HP-Pavilion-15-Notebook-PC:~/Desktop/numpy-threading-extensions$ rever 0.0.0
Activity 'changelog' has already been completed!
Activity 'push_tag' has already been completed!
Activity 'tag' has already been completed!
Activity 'version_bump' has already been completed!
activity-start:ghrelease:starting activity ghrelease
/home/dale/anaconda3/lib/python3.8/site-packages/github3/session.py:3: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated since Python 3.3, and in 3.9 it will stop working
  from collections import Callable
/home/dale/anaconda3/lib/python3.8/site-packages/github3/structs.py:11: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated since Python 3.3, and in 3.9 it will stop working
  class GitHubIterator(models.GitHubCore, collections.Iterator):
activity-error:ghrelease:activity failed with execption:
Traceback (most recent call last):
  File "/home/dale/anaconda3/lib/python3.8/site-packages/rever/github.xsh", line 164, in create_or_get_release
    rel = repo.create_release(
  File "/home/dale/anaconda3/lib/python3.8/site-packages/github3/decorators.py", line 31, in auth_wrapper
    return func(self, *args, **kwargs)
  File "/home/dale/anaconda3/lib/python3.8/site-packages/github3/repos/repo.py", line 1204, in create_release
    json = self._json(self._post(url, data=data), 201)
  File "/home/dale/anaconda3/lib/python3.8/site-packages/github3/models.py", line 156, in _json
    raise exceptions.error_for(response)
github3.exceptions.UnprocessableEntity: 422 Validation Failed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/dale/anaconda3/lib/python3.8/site-packages/rever/activity.xsh", line 83, in __call__
    self.func(*args, **kwargs)
  File "/home/dale/anaconda3/lib/python3.8/site-packages/rever/activities/ghrelease.xsh", line 99, in _func
    rel = github.create_or_get_release(repo, name, name,
  File "/home/dale/anaconda3/lib/python3.8/site-packages/rever/github.xsh", line 173, in create_or_get_release
    rel = repo.release_from_tag(tag_name)
  File "/home/dale/anaconda3/lib/python3.8/site-packages/github3/repos/repo.py", line 2501, in release_from_tag
    json = self._json(self._get(url), 200)
  File "/home/dale/anaconda3/lib/python3.8/site-packages/github3/models.py", line 156, in _json
    raise exceptions.error_for(response)
github3.exceptions.NotFoundError: 404 Not Found

```

**Comment by daletovar** [comment]
Here's the .xsh that I'm using:
```
$PROJECT = 'fast-numpy-loops'
$ACTIVITIES = [
              'version_bump',  # Changes the version number in various source files (setup.py, __init__.py, etc)
              'changelog',  # Uses files in the news folder to create a changelog for release
              'tag',  # Creates a tag for the new version number
              'push_tag',  # Pushes the tag up to the $TAG_REMOTE
              'ghrelease'  # Creates a Github release entry for the new tag
               ]
$VERSION_BUMP_PATTERNS = [  # These note where/how to find the version numbers
                         ('setup.py', r'version\s*=.*,', "version='$VERSION',")
                         ]
$CHANGELOG_FILENAME = 'CHANGELOG.rst'  # Filename for the changelog
$CHANGELOG_TEMPLATE = 'TEMPLATE.rst'  # Filename for the news template
$PUSH_TAG_REMOTE = 'git@github.com:Quansight/numpy-threading-extensions.git'  # Repo to push tags to

$GITHUB_ORG = 'Quansight'  # Github org for Github releases and conda-forge
$GITHUB_REPO = 'numpy-threading-extensions'  # Github repo for Github releases  and conda-forge
```

**Comment by kcpevey** [comment]
can you post the output from `rever check`?

**Comment by kcpevey** [comment]
it looks like you're trying to release to a tag that already exists. Try version 0.0.3

**Comment by daletovar** [comment]
```
(base) dale@dale-HP-Pavilion-15-Notebook-PC:~/Desktop/numpy-threading-extensions$ rever check
No checks needed for version_bump activity
No checks needed for changelog activity
No checks needed for tag activity
All CLI and import requirements met for push_tag activity
Initialized empty Git repository in /home/dale/Desktop/numpy-threading-extensions/rever/git-have-push-perm/.git/
~/Desktop/numpy-threading-extensions/rever/git-have-push-perm ~/Desktop/numpy-threading-extensions
Switched to a new branch '__rever__'
[__rever__ (root-commit) 5ed3eb5] Checking rever permissions
Enumerating objects: 2, done.
Counting objects: 100% (2/2), done.
Writing objects: 100% (2/2), 176 bytes | 176.00 KiB/s, done.
Total 2 (delta 0), reused 0 (delta 0)
remote: 
remote: Create a pull request for '__rever__' on GitHub by visiting:
remote:      https://github.com/Quansight/numpy-threading-extensions/pull/new/__rever__
remote: 
To github.com:Quansight/numpy-threading-extensions.git
 * [new branch]      __rever__ -> __rever__
To github.com:Quansight/numpy-threading-extensions.git
 - [deleted]         __rever__
~/Desktop/numpy-threading-extensions
activity-check:push_tag:Checked activity push_tag
/home/dale/anaconda3/lib/python3.8/site-packages/github3/session.py:3: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated since Python 3.3, and in 3.9 it will stop working
  from collections import Callable
/home/dale/anaconda3/lib/python3.8/site-packages/github3/structs.py:11: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated since Python 3.3, and in 3.9 it will stop working
  class GitHubIterator(models.GitHubCore, collections.Iterator):
All CLI and import requirements met for ghrelease activity
GitHub login as daletovar works!
activity-check:ghrelease:Checked activity ghrelease

```

**Comment by daletovar** [comment]
I run into the same exception when I use 0.0.3.

**Comment by kcpevey** [comment]
Closing since this has been superceded. It was impossible to test the github release mechanism from a fork.

**Pull request closed without merging**
