### PR TITLE
Fix loop variable ref issue in ufunc benchmarks.

### PR DESCRIPTION
**Pull request by jack-pappas**
This PR fixes an issue I pointed out in #107 where the loop variable (the ufunc name) was referenced from within the constructed benchmark classes, which meant all of the classes ended up running the same ufunc -- the last one in the list -- rather than whichever one they were supposed to be benchmarking. The ufunc is now assigned to a class attribute on each of the benchmark classes, and each class retrieves it from there avoiding capture issues.

I also defined ``__slots__`` for the constructed ufunc benchmark classes to shave off a little overhead (from attribute lookups) within the benchmark methods. It's likely negligible, but every little bit of overhead that can be removed helps make the benchmark results as accurate as possible.

### CODE REVIEW

**Comment by mattip** [comment]
I have tried running `asv run` on two different linux machines (AMD Ryzen 9 3900X and Intel i7-7700) and the benchmarks run __very__ slowly. Is there a way to speed them up?

**Comment by mattip** [comment]
Even running `asv run -q`, which should only run each benchmark once, takes ages. Maybe some restructuring is needed? it seems each ufunc is being run for `atop` * `nthreads` * `rank` * `dtype` times, where
- `atop in [True, False]`
- `nthreads in [0, 2, 4]`
- `rank in range(2)`
- `dtype in ['int16', 'float16', 'int32', 'float32', 'int64', 'float64',  'complex64', 'longfloat', 'complex128', 'complex256']` (10 values)
for a total of 2 * 3 * 2 * 10 or 120 runs. Is there a way to limit that to, say, `dtype='float64'` and `rank==1` ?

**Comment by mattip** [comment]
maybe I can run with `asv run -a ...`

**Comment by mattip** [comment]
nope. There is no interface to select parameters for a benchmark.

**Comment by jack-pappas** [comment]
I ran the benchmark suite on my home machine last night, it took 4-5 hours. I like being able to run a very detailed benchmark suite on occasion to see if there's anything unusual in the data (e.g. some function runs 2x faster for ``int32`` vs. ``uint32``), but I agree it'd be better to have a smaller set of parameters for when someone just wants to do a quick run (or something we might decide to run as part of a CI process in the future).

It's unfortunate asv doesn't have a straightforward way to run the benchmark suite with some subset of the parameter values. Maybe we could hack something in with an environment variable like this comment mentioned: https://github.com/airspeed-velocity/asv/issues/791#issuecomment-645006759

**Pull request merged**
